---
####################################################
#          ModuleBuilder Configuration             #
####################################################
BuiltModuleSubdirectory: module
CopyPaths:
  - en-US
  - Lib
Encoding: UTF8

VersionedOutputDirectory: true

####################################################
#      ModuleBuilder Submodules Configuration      #
####################################################
Prefix: Prefix.ps1

####################################################
#       Sampler Pipeline Configuration             #
####################################################
BuildWorkflow:
  ".":
    - build
    - test

  build:
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder
    - Create_changelog_release_output

  pack:
    - build
    - package_module_nupkg

  hqrmtest:
    - DscResource_Tests_Stop_On_Fail

  test:
    - Pester_Tests_Stop_On_Fail
    - Pester_if_Code_Coverage_Under_Threshold

  merge:
  - Merge_CodeCoverage_Files

  publish:
    - publish_module_to_gallery
    - Publish_Release_To_GitHub

ModuleBuildTasks:
  Sampler:
    - "*.build.Sampler.ib.tasks"
  Sampler.GitHubTasks:
    - "*.ib.tasks"

TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""


####################################################
#           Pester Configuration                   #
####################################################
Pester:
  OutputFormat: NUnitXML
  ExcludeFromCodeCoverage:

  Script:
  # - tests/QA/module.tests.ps1
  # - tests/QA
  # - tests/Unit
  # - tests/Integration
  ExcludeTag:
  #  - helpQuality
  #  - FunctionalQuality
  #  - TestQuality
  Tag:
  CodeCoverageThreshold: 5

####################################################
#             HQRM Test Configuration              #
####################################################

DscTest:
  Pester:
    Configuration:
      Filter:
        ExcludeTag:
          - Common Tests - New Error-Level Script Analyzer Rules
          - Common Tests - Validate Localization
          - Common Tests - Validate Example Files To Be Published
          - Common Tests - Validate Example Files
          - RequiredPSSA
      Output:
        Verbosity: Detailed
        CIFormat: Auto
      TestResult:
        OutputFormat: NUnitXML
        OutputEncoding: ascii
        OutputPath: ./output/testResults/NUnitXml_HQRM_Tests.xml
  Script:
    ExcludeSourceFile:
      - output
      - Modules/DscResource.Common
    ExcludeModuleFile:
      - Templates
      - Modules/DscResource.Common
    MainGitBranch: main
